--[[--------------------------------------------------------------------
	Broker_TicketStatus
	Shows the status of your GM Help Ticket on your DataBroker display.
	Copyright (c) 2011-2015 Phanx <addons@phanx.net>. All rights reserved.
	http://www.wowinterface.com/downloads/info20888-BrokerTicketStatus.html
	http://www.curse.com/addons/wow/broker-ticketstatus
	https://github.com/Phanx/Broker_TicketStatus
----------------------------------------------------------------------]]

local ADDON, L = ...

L["Open a ticket"] = gsub(HELP_TICKET_OPEN, "|n", " "), -- deDE includes a line break -_-

setmetatable(L, { __index = function(t, k)
	local v = tostring(k)
	t[k] = v
	return v
end })

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED. SEE:
-- http://wow.curseforge.com/addons/broker-ticketstatus/localization/

------------------------------------------------------------------------
-- English
------------------------------------------------------------------------

local CURRENT_LOCALE = GetLocale()
if CURRENT_LOCALE == "enUS" then return end

------------------------------------------------------------------------
-- German
------------------------------------------------------------------------

if CURRENT_LOCALE == "deDE" then

L["Alert color"] = "Bekanntmachungsfarbe"
L["Click to edit your ticket."] = "Linksklick, um Ihr Ticket bearbeiten."
L["Click to open a new ticket."] = "Linksklick, um ein Ticket eröffnen."
L["Middle-click to abandon your ticket."] = "Mittellick, um Ihr Ticket verlassen."
L["Needs more info!"] = "Mehr Info benötigt!"
L["Open"] = "Offene"
L["Response!"] = "Antwort!"
L["Right-click for options."] = "Rechtsklick für Optionen."
L["Show status change alerts"] = "Statusänderungsbekanntmachungen"
L["Show text without ticket"] = "Text ohne offenes Ticket"
L["Survey!"] = "Umfrage!"
L["Ticket Status"] = "Ticketstatus"

return end

------------------------------------------------------------------------
-- Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esES" then

L["Alert color"] = "Color de avisos"
L["Click to edit your ticket."] = "Clic para editar tu consulta."
L["Click to open a new ticket."] = "Clic para abrir una nueva consulta."
L["Middle-click to abandon your ticket."] = "Clic medio para abandonar tu consulta."
L["Needs more info!"] = "Requiere más info!"
L["Open"] = "Abierta"
L["Response!"] = "¡Respuesta!"
L["Right-click for options."] = "Clic derecho para opciones."
L["Show status change alerts"] = "Avisos para cambios de estado"
L["Show text without ticket"] = "Texto sin consulta abierta"
L["Survey!"] = "¡Encuesta!"
L["Ticket Status"] = "Estado de consulta"

return end

------------------------------------------------------------------------
-- Latin American Spanish
------------------------------------------------------------------------

if CURRENT_LOCALE == "esMX" then

L["Alert color"] = "Color de avisos"
L["Click to edit your ticket."] = "Clic para editar tu consulta."
L["Click to open a new ticket."] = "Clic para abrir una nueva consulta."
L["Middle-click to abandon your ticket."] = "Clic medio para abandonar tu consulta."
L["Needs more info!"] = "Requiere más info!"
L["Open"] = "Abierta"
L["Response!"] = "¡Respuesta!"
L["Right-click for options."] = "Clic derecho para opciones."
L["Show status change alerts"] = "Avisos para cambios de estado"
L["Show text without ticket"] = "Texto sin consulta abierta"
L["Survey!"] = "¡Encuesta!"
L["Ticket Status"] = "Estado de consulta"

return end

------------------------------------------------------------------------
-- French
------------------------------------------------------------------------

if CURRENT_LOCALE == "frFR" then

return end

------------------------------------------------------------------------
-- Italian
------------------------------------------------------------------------

if CURRENT_LOCALE == "itIT" then

return end

------------------------------------------------------------------------
-- Brazilian Portuguese
------------------------------------------------------------------------

if CURRENT_LOCALE == "ptBR" then

L["Alert color"] = "Cor de alertas"
L["Click to edit your ticket."] = "Clique para editar sua consulta."
L["Click to open a new ticket."] = "Clique para abrir uma nova consulta de MJ."
L["Middle-click to abandon your ticket."] = "Clique com o botão do meio para abandonar sua consulta."
L["Needs more info!"] = "Necessária mais info!"
L["Open"] = "Aberta"
L["Response!"] = "Reposta!"
L["Right-click for options."] = "Clique com o botão direito para opções."
L["Show status change alerts"] = "Alertas de mudanças de estado da consulta"
L["Show text without ticket"] = "Texto quando não há consultar"
L["Survey!"] = "Pesquisa!"
L["Ticket Status"] = "Estado de consulta"

return end

------------------------------------------------------------------------
-- Russian
------------------------------------------------------------------------

if CURRENT_LOCALE == "ruRU" then

L["Alert color"] = "Цвет оповещений"
L["Click to open a new ticket."] = "Нажмите чтобы ввести новый запрос"
L["Needs more info!"] = "Нужно больше информации!"
L["Open"] = "Открыть"
L["Response!"] = "Вам ответили!"
L["Right-click for options."] = "Щелкните ПКМ чтобы открыть настройки"
L["Show status change alerts"] = "Уведомить об изменении статуса"
L["Show text without ticket"] = "Показать текст без запроса"
L["Survey!"] = "Опрос!"
L["Ticket Status"] = "Статус запроса"

return end

------------------------------------------------------------------------
-- Korean
------------------------------------------------------------------------

if CURRENT_LOCALE == "koKR" then

return end

------------------------------------------------------------------------
-- Simplified Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhCN" then

L["Alert color"] = "提示颜色"
L["Click to open a new ticket."] = "点击开启一个新的回报单。"
L["Needs more info!"] = "需要更多信息!"
L["Open"] = "开启"
L["Response!"] = "回应!"
L["Right-click for options."] = "右键点击开启选项。"
L["Show status change alerts"] = "显示状态变化提示"
L["Show text without ticket"] = "显示无回报单文字"
L["Survey!"] = "调查中!"
L["Ticket Status"] = "回报单状态"

return end

------------------------------------------------------------------------
-- Traditional Chinese
------------------------------------------------------------------------

if CURRENT_LOCALE == "zhTW" then

L["Alert color"] = "提示顏色"
L["Click to open a new ticket."] = "點擊開啟一個新的回報單。"
L["Needs more info!"] = "需要更多資訊!"
L["Open"] = "開啟"
L["Response!"] = "回應!"
L["Right-click for options."] = "右鍵點擊開啟選項。"
L["Show status change alerts"] = "顯示狀態變化提示"
L["Show text without ticket"] = "顯示無回報單文字"
L["Survey!"] = "調查中!"
L["Ticket Status"] = "回報單狀態"

return end
